name: wordpress
recipe: wordpress
env_file:
  - .env
config:
  webroot: wp
  php: "7.2"
  via: nginx
  database: mariadb
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/tutorials/php.html#toggling-xdebug
  xdebug: true
  config:
    vhosts: .nginx-wordpress.conf
    php: php.ini
services:
  appserver:
    run:
      - bash /app/bin/setup.sh
    build_as_root:
      - apt-get update -y && apt-get install -y subversion
    composer:
      phpunit/phpunit: "^6"
  node:
    type: node
    overrides:
      ports:
        - 3000:3000
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
  php:
    service: appserver
  composer:
    service: appserver
  npm:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  # workflow command shortcuts
  build:
    service: node
    cmd: npm start
  watch:
    service: node
    cmd: npm run watch
